apiVersion: v1
kind: Service
metadata:
  name: officegif
  namespace: officegif-dev
  labels:
    app: officegif
    env: dev
spec:
  selector:
    app: officegif
  ports:
    - port: 80
      targetPort: 5000
  type: LoadBalancer