apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: officegif-external-secret
  namespace: dev
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-backend          
  target:                                                             
    name: officegif
  data:                                                       
  - secretKey: SECRETCODE
    remoteRef:            
      key: secertcode
