apiVersion: apps/v1
kind: Deployment
metadata:
  name:  officegif
  namespace: officegif-dev
  labels:
    app: officegif
    env: dev
    release: v1.0.0
spec:
  selector:
    matchLabels:
      app: officegif
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: officegif
    spec:
      containers:
      - name:  officegif
        image:  gcr.io/officegif/officegif:4f95d3ca191aabfcc37a7c1f39a6dad4005731a3
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        env:
        - name: MESSAGE
          valueFrom:
            configMapKeyRef:
              name: officegif
              key: MESSAGE
        - name: GIPHY_API_KEY
          valueFrom:
            secretKeyRef:
              name: officegif
              key: GIPHY_API_KEY
        ports:
        - containerPort: 5000
          name: officegif-app
      restartPolicy: Always